<?php
use DaoNguyen\Community\Block\Group\Item;

/** @var Item $block */
$group = $block->getGroup();
?>
<div class="group-card-item">
    <div class="card-container">
        <a href="#">
            <div class="group-details">
                <img class="group-avatar" src="<?= $block->escapeHtmlAttr($group->getAvatarUrl()) ?>" alt="Group Avatar">
                <h4 class="group-name"><?= $block->escapeHtml($group->getName()) ?></h4>
                <div class="group-description"><?= $block->escapeHtml($block->truncateDescription($group->getDescription())) ?></div>
            </div>
        </a>
        <form action="<?= $block->getUrl('community/member/join') ?>" method="post" id="join-group">
            <input type="hidden" name="group_id" value="<?= $group->getId() ?>">
        </form>
        <div class="actions-toolbar">
            <div class="primary"><button type="submit" form="join-group" value="Join"
                    <?php if ($block->isMemberJoin($group->getEntityId())): ?><?= "disabled" ?><?php endif; ?>
                >Join</button></div>
        </div>
    </div>
</div>
