<?php
use DaoNguyen\Community\Block\Group\Item;

/** @var Item $block */
$group = $block->getGroup();
$formId = 'form-' . $group->getId();
$scope = 'button-join-' . $group->getId();
?>
<div class="group-card-item">
    <div class="card-container">
        <a href="<?= $block->escapeUrl($block->getUrl('community/group/view', ['id' => $group->getId()])) ?>">
            <div class="group-details">
                <img class="group-avatar" src="<?= $block->escapeHtmlAttr($group->getAvatarUrl()) ?>" alt="Group Avatar">
                <h4 class="group-name"><?= $block->escapeHtml($group->getName()) ?></h4>
                <div class="group-description"><?= $block->escapeHtml($block->truncateDescription($group->getDescription())) ?></div>
            </div>
        </a>
        <form action="<?= $block->getUrl('community/member/join') ?>" method="post" id="<?= $formId ?>">
            <input type="hidden" name="group_id" value="<?= $group->getId() ?>">
        </form>
        <div class="actions-toolbar" data-bind="scope: '<?= $scope ?>'">
            <div class="primary"><button data-bind="disable: isJoined()" type="submit" form="<?= $formId ?>" value="Join">Join</button></div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".actions-toolbar": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "<?= $scope ?>": {
                        "component": "DaoNguyen_Community/js/view/join-button",
                        "groupId": "<?= $group->getId() ?>"
                    }
                }
            }
        }
    }
</script>
