<?php
/** @var \Magento\Framework\View\Element\Template $block */

?>
<div class="community-home"">
    <div class="posts-header">All Posts</div>
    <div class="container">
        <div class="column left">
            <?= $block->getChildHtml('community.home.post.list.orders') ?>
        </div>
        <div class="column middle">
            <?= $block->getChildHtml('community.home.post.list') ?>
            <?= $block->getChildHtml('post_pager') ?>
        </div>
        <div class="column right">
            <div class="right-sidebar">
                <?= $block->getChildHtml('community.attached.posts')?>
            </div>
        </div>
    </div>
</div>
