<nav class="navigation" data-action="navigation">
    <ul id="menu" data-mage-init='{"menu":{"responsive":true, "expanded":true, "delay": 200, "position":{"my":"left top","at":"left+10 top+30"}}}'>
        <li class="level0 level-top ui-menu-item">Community</li>
        <li class="level0 level-top ui-menu-item">Profile</li>
        <li class="level0 level-top ui-menu-item">Group</li>
        <li class="level0 level-top ui-menu-item">Gallery</li>
    </ul>
</nav>
