<?php
/** @var Template $block */
use Magento\Framework\View\Element\Template;
?>
<div class="community-nav">
    <nav class="navbar">
        <ul class="nav-links">
            <li class="nav-item"><a href="<?= $block->getUrl('community') ?>">Community</a></li>
            <li class="nav-item"><a href="<?= $block->getUrl('community/member') ?>">Profile</a></li>
            <li class="nav-item"><a href="<?= $block->getUrl('community/group/all') ?>">Groups</a></li>
            <li class="nav-item"><a href="<?= $block->getUrl('community/member/gallery') ?>">Gallery</a></li>
        </ul>
        <ul class="nav-links">
            <li class="nav-item"><a href="<?= $block->getUrl('community/post/create') ?>">Create a Post</a></li>
<!--            <li class="nav-item"><a href="#">Add a Photo</a></li>-->
            <li class="nav-item">
                <div data-bind="scope: 'notifications'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
            </li>
        </ul>
    </nav>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "notifications": {
                        "component": "DaoNguyen_Community/js/notifications",
                        "template": "DaoNguyen_Community/notifications"
                    }
                }
            }
        }
    }
</script>
