<?php
/** @var \DaoNguyen\Community\Block\Post\Comment\View $block */
/** @var \Magento\Framework\Escaper $escaper */
$comment = $block->getComment();
?>
<div class="comment-view-wrapper">
    <div class="comment">
        <div class="header">
            <div class="author">
                <img class="avatar" src="<?= $escaper->escapeUrl($block->getAvatarAuthorUrl()) ?>" alt="avatar">
                <div class="nickname"><?= $escaper->escapeHtml($comment->getMember()->getNickname()) ?></div>
                <div class="badges"></div>
            </div>
            <div class="updated-at"><?= $escaper->escapeHtml($comment->getUpdatedAt()) ?></div>
        </div>
        <div class="main">
            <?= $comment->getContent() ?>
        </div>
        <div class="footer">
            <a href="<?= $escaper->escapeUrl($block->getUrl('community/post/comment_create', ['post_id' => $comment->getPostId() ,'comment_id' => $comment->getEntityId()])) ?>">
                <div class="reply">
                    <label><?= $escaper->escapeHtml('Reply') ?></label>
                </div>
            </a>
        </div>
    </div>
</div>
