<?php
use DaoNguyen\Community\Block\Wysiwyg\Images\Content;
/** @var Content $block */
?>
<div class="media-gallery-modal">
    <div class="actions">
        <div class="action-buttons">
            <button id="cancel" title="Cancel" type="button" class="action-default action-quaternary" onclick="MediabrowserUtility.closeDialog()">
                <span>Cancel</span>
            </button>
            <button id="insert_images" title="Add Selected" type="button" class="action-default save no-display action-primary">
                <span>Add Selected</span>
            </button>
        </div>
    </div>
    <div class="main-col">
        <div id="contents-uploader" class="contents-uploader">
            <div id="uploader" class="uploader">
                <span class="fileinput-button form-buttons">
                    <span><?= $block->escapeHtml(__('Upload Images')) ?></span>
                    <input class="fileupload" type="file"
                           name="image"
                           data-url="<?= $block->getUrl('community/wysiwyg_images/upload') ?>" multiple>
                </span>
            </div>
        </div>
        <div id="contents"></div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".media-gallery-modal": {
            "DaoNguyen_Community/js/view/media-modal": {
                "maxFileSize": 104857600,
                "maxWidth": 1920,
                "maxHeight": 1200,
                "isResizeEnabled": 1,
                "contentsUrl": "<?= $block->getUrl('community/wysiwyg_images/contents') ?>"
            }
        }
    }
</script>
