<?php
use DaoNguyen\Community\Block\Wysiwyg\Images\Uploader;
/** @var Uploader $block */
?>
<div id="uploader" class="uploader"
     data-mage-init='{
        "DaoNguyen_Community/js/view/media-uploader": {
            "maxFileSize": 104857600,
            "maxWidth": 1920,
            "maxHeight": 1200,
            "isResizeEnabled": 1
        }
     }'
>
    <span class="fileinput-button form-buttons">
        <span><?= $block->escapeHtml(__('Upload Images')) ?></span>
        <input class="fileupload" type="file"
               name="image"
               data-url="" multiple>
    </span>
    <div class="clear"></div>
    <script type="text/x-magento-template" id="uploader-template" data-template="uploader">
        <div id="<%- data.id %>" class="file-row">
            <span class="file-info"><%- data.name %> (<%- data.size %>)</span>
            <div class="progressbar-container">
                <div class="progressbar upload-progress" style="width: 0;"></div>
            </div>
            <div class="clear"></div>
        </div>
    </script>
</div>
