<?php
/** @var \DaoNguyen\Community\Block\Post\Preview $block */
/** @var \Magento\Framework\Escaper $escaper */
$post = $block->getPost();
$recentComment = $block->getRecentComment();
?>
<div class="post-preview-container">
    <div class="post-preview">
        <div class="location">
            <span><?= $escaper->escapeHtml(__('Post in')) ?></span>
            <a href="#"><strong><?= $post->getGroup()->getName() ?></strong></a>
        </div>
        <div class="subject">
            <a href="<?= $escaper->escapeUrl($block->getUrl('community/post/view', ['id' => $post->getId()])) ?>"><p><?= $escaper->escapeHtml($post->getSubject()) ?></p></a>
        </div>
        <div class="time-details">
            <span><?= $escaper->escapeHtml(__('Posted')) ?></span>
            <span><?= $post->getCreatedAt() ?></span>
            <span>|</span>
            <span><?= $escaper->escapeHtml(__('Updated')) ?></span>
            <span><?= $post->getUpdatedAt() ?></span>
        </div>
        <div class="author">
            <img class="avatar" src="<?= $escaper->escapeUrl($block->getAvatarAuthorUrl($post->getMember())) ?>" alt="avatar">
            <div class="nickname"><?= $escaper->escapeHtml($post->getMember()->getNickname()) ?></div>
            <div class="badges"></div>
        </div>
        <div class="preview-content">
            <?= $block->truncate($post->getContent()) ?>
        </div>
        <div class="recent-comment-preview">
            <div class="recent-comment">
                <div class="header">
                    <div class="author">
                        <img class="avatar" src="<?= $escaper->escapeUrl($block->getAvatarAuthorUrl($recentComment->getMember())) ?>" alt="avatar">
                        <div class="nickname"><?= $escaper->escapeHtml($recentComment->getMember()->getNickname()) ?></div>
                        <div class="badges"></div>
                    </div>
                    <div class="updated-at"><?= $escaper->escapeHtml($recentComment->getUpdatedAt()) ?></div>
                </div>
                <div class="comment-preview-content">
                    <?= $block->truncate($recentComment->getContent()) ?>
                </div>
            </div>
        </div>
        <div class="recent-images">

        </div>
        <div class="actions">
            <div class="kudos" data-bind="scope: 'kudos'">
                <div data-bind="class: currentStatusClass, click: reaction">
                    <label><?= $escaper->escapeHtml(__('Like')) ?></label>
                </div>
            </div>
            <a href="<?= $block->getUrl('community/post/comment_create', ['post_id' => $post->getEntityId()]) ?>">
                <div class="reply">
                    <label><?= $escaper->escapeHtml(__('Reply')) ?></label>
                </div>
            </a>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "kudos": {
                        "component": "DaoNguyen_Community/js/view/kudos",
                        "postId": "<?= $post->getEntityId() ?>"
                    }
                }
            }
        }
    }
</script>
