<?php
declare(strict_types=1);

namespace DaoNguyen\Community\Model\Rule\Condition;

use DaoNguyen\Community\Api\MemberRepositoryInterface;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\Exception\NoSuchEntityException;
use Magento\Framework\Serialize\SerializerInterface;
use Magento\Rule\Model\Condition\AbstractCondition;
use Magento\Rule\Model\Condition\Context;

class Rank extends AbstractCondition
{
    private ScopeConfigInterface $scopeConfig;

    private SerializerInterface $serializer;

    private MemberRepositoryInterface $memberRepository;

    public function __construct(
        ScopeConfigInterface $scopeConfig,
        SerializerInterface $serializer,
        MemberRepositoryInterface $memberRepository,
        Context $context,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->scopeConfig = $scopeConfig;
        $this->serializer = $serializer;
        $this->memberRepository = $memberRepository;
    }

    public function loadAttributeOptions()
    {
        $attributes = [
            'member_rank' => __('Rank')
        ];

        $this->setAttributeOption($attributes);

        return $this;
    }

    public function getInputType()
    {
        return 'select';
    }

    public function getValueElementType()
    {
        return 'select';
    }

    public function getValueSelectOptions()
    {
        if (!$this->hasData('value_select_options')) {
            $this->setData('value_select_options', $this->getRankOptions());
        }
        return $this->getData('value_select_options');
    }

    protected function getRankOptions()
    {
        $options = [];
        $rankConfig = $this->scopeConfig->getValue('community_rank_system/configuration/ranks');
        $rankConfig = $this->serializer->unserialize($rankConfig);
        foreach ($rankConfig as $value => $label) {
            $options[] = [
                'label' => $label,
                'value' => $value
            ];
        }
        return $options;
    }

    public function validate(\Magento\Framework\Model\AbstractModel $model)
    {
        $customerId = (int) $model->getCustomerId();
        if ($customerId) {
            try {
                $member = $this->memberRepository->getByCustomerId($customerId);
                $points = $member->getRankPoints();
                $rank = 0;
                $rankConfig = $this->scopeConfig->getValue('community_rank_system/configuration/ranks');
                $rankConfig = $this->serializer->unserialize($rankConfig);
                ksort($rankConfig);
                foreach ($rankConfig as $key => $label) {
                    if ($points > $key) {
                        $rank = $key;
                    } else {
                        break;
                    }
                }
                $model->setData('member_rank', $rank);
            } catch (NoSuchEntityException) {
                return parent::validate($model);
            }
        }
        return parent::validate($model); // TODO: Change the autogenerated stub
    }
}
