<?php
declare(strict_types=1);

namespace DaoNguyen\Community\Block\Group\View;

use DaoNguyen\Community\Model\ResourceModel\Post\Collection;

class Posts extends GroupView
{
    /** @var Collection */
    private $postCollection;

    protected function _prepareLayout()
    {
        $collection = $this->getPostCollection();
        $collection->addFieldToFilter('group_id', ['id' => $this->getGroup()->getEntityId()]);
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function getPostListHtml()
    {
        return $this->getChildHtml('post.list');
    }

    public function getListBlock()
    {
        return $this->getChildBlock('post.list');
    }

    /**
     * @return Collection
     */
    public function getPostCollection()
    {
        if ($this->postCollection === null) {
            $this->postCollection = $this->getListBlock()->getPostCollection();
            $this->postCollection->addFieldToFilter('group_id', ['eq' => $this->getGroup()->getEntityId()]);
        }
        return $this->postCollection;
    }

    public function getResultCount()
    {
        if (!$this->getData('result_count')) {
            $size = $this->getPostCollection()->getSize();
            $this->setResultCount($size);
        }
        return $this->getData('result_count');
    }
}
