<?php
/** @var \DaoNguyen\Community\Block\Post\View\PostView $block */
/** @var \Magento\Framework\Escaper $escaper */
$post = $block->getPost();
$member = $post->getMember()
?>
<div class="post-content" xmlns="http://www.w3.org/1999/html">
    <div class="post-in">
        <span><?= $escaper->escapeHtml(__('Post In')) ?></span>
        <a href="#"><strong><?= $block->getGroupName() ?></strong></a>
    </div>
    <div class="post-time-details">
        <span><?= $escaper->escapeHtml(__('Posted')) ?></span>
        <span><?= $post->getCreatedAt() ?></span>
        <span>|</span>
        <span><?= $escaper->escapeHtml(__('Updated')) ?></span>
        <span><?= $post->getUpdatedAt() ?></span>
    </div>
    <div class="post-author">
        <img class="avatar" src="<?= $escaper->escapeUrl($block->getAvatarAuthorUrl()) ?>" alt="avatar">
        <div class="nickname"><?= $escaper->escapeHtml($member->getNickname()) ?></div>
        <div class="badges"></div>
    </div>
    <div class="post-subject">
        <h2><?= $post->getSubject() ?></h2>
    </div>
    <div class="content">
        <?= $post->getContent() ?>
    </div>
    <div class="action">
        <div class="kudos" data-bind="scope: 'kudos'">
            <div data-bind="class: currentStatusClass, click: reaction">
                <label><?= $escaper->escapeHtml('Like') ?></label>
            </div>
        </div>
        <a href="<?= $block->getUrl('community/post/comment_create', ['post_id' => $post->getEntityId()]) ?>">
            <div class="reply">
                <label><?= $escaper->escapeHtml('Reply') ?></label>
            </div>
        </a>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "kudos": {
                        "component": "DaoNguyen_Community/js/view/kudos",
                        "postId": "<?= $post->getEntityId() ?>"
                    }
                }
            }
        }
    }
</script>
